name: Deploy to VPS

on:
  push:
    branches:
      - main  # Este pipeline se ejecutará cuando haya un push en la rama 'main'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[frontend]') || contains(github.event.head_commit.message, '[both]')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
        chmod +x ./add_ssh_key.sh
        ./add_ssh_key.sh
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

    - name: Copy frontend files to VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./frontend ${VPS_USER}@${VPS_HOST}:/var/www/lstapp/
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./docker-compose.yml ${VPS_USER}@${VPS_HOST}:/var/www/lstapp/

    - name: Deploy frontend on VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} << 'EOF'
        cd /path/to/your/project/on/vps
        docker-compose build frontend
        docker-compose up -d frontend
        EOF

  deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[backend]') || contains(github.event.head_commit.message, '[both]')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y expect
        chmod +x ./add_ssh_key.sh
        ./add_ssh_key.sh
      env:
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

    - name: Copy backend files to VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./backend ${VPS_USER}@${VPS_HOST}:/var/www/lstapp/
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./docker-compose.yml ${VPS_USER}@${VPS_HOST}:/var/www/lstapp/

    - name: Deploy backend on VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_HOST} << 'EOF'
        cd /path/to/your/project/on/vps
        docker-compose build backend
        docker-compose up -d backend
        EOF
